version: "3.9"

services:
  database:
    image: postgres:16
    container_name: db-jerney0
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

    tmpfs:
      - /tmp
      - /run
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - internal

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: backend-jerney0
    restart: unless-stopped

    environment:
      PORT: 5000
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
    expose:
      - "5000"
    depends_on:
      - database

    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - internal

  frontend:
    build:
      context: ./frontend
    container_name: frontend-jerney0
    restart: unless-stopped
    ports:
      - "80:8080"
    depends_on:
      - backend

    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - internal

volumes:
  pgdata:

networks:
  internal:
    driver: bridge