# ==============================================================
# Pipelines: Infra Automation
# This workflow automates the provisioning of infrastructure components in terraform file
# ==============================================================

name: Infra Automation

on :
  push:
    branches: 
      - main
      - staging
      - dev
    paths:
      - 'terraform/**'
  pull_request:
    branches:
      - main
      - staging
      - dev 
    paths:
      - 'terraform/**'

permissions:
  contents: read
  pull-requests: write
  issues: write


env:
  TF_LOG: INFO
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
    terraform-plan:
      name: Terraform Plan
      runs-on: ubuntu-latest
      outputs:
        terraform-workspace: ${{ steps.env-vars.outputs.tf-workspace }}
      defaults:
        run:
          shell: bash
          working-directory: /terraform/**

      steps:
       - name: Checkout code
         uses: actions/checkout@v4
      
       - name: set up Terraform
         uses: hashicorp/setup-terraform@v3
         with:
           terraform_version: v1.13.3

       - name: Setup tflint
         uses: terraform-linters/setup-tflint@v3
         with:
          terraform_version: v0.52.0

       - name: Init TFlint
         env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: tflint --init

       - name: Run TFlint
         env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: tflint -f compact
         
       - name: Trivy Scanner in Iac mode
         uses: aquasecurity/trivy-action@master
         with:
           scan-type: "config"
           hide-progress: true
           format: table
           output: trivy-iac.txt
           exit-code: "0"
           ignore-unfixed: true
           severity: "CRITICAL,HIGH"

       - name: Terraform Init
         id: init
         run: terraform init

       - name: Terraform format check
         id: fmt
         run: terraform fmt -check
  
       - name: Terraform validate
         id: validate
         run: terraform validate

       - name: Set up Terraform workspace
         id: env-vars
         run: |
           if [[ ${{github.event_name}} == "pull_request"]]; then
              BRANCH_NAME="${{ github.base_ref }}"
           else
              BRANCH_NAME="${{ github.ref_name }}"
           fi


           if [[ "$BRANCH_NAME == main" ]]; then
              echo "WORKSPACE_NAME=production" >> $GITHUB_ENV
              echo "tf_workspace=production" >> $GITHUB_OUTPUT
              echo "TF_VARS_FILE=production.tfvars" >> $GITHUB_ENV
           elif [[ $BRANCH_NAME == staging" ]]; then
              echo "WORKSPACE_NAME=stagiing " >> $GITHUB_ENV
              echo "tf_workspace=staging" >> $GITHUB_OUTPUT
              echo "TF_VARS_FILE=staging.tfvars" >> $GITHUB_ENV
            fi

       - name: Select Terraform workspace
         id: workspace
         run: terraform workspace select $WORKSPACE_NAME || terraform workspace new $WORKSPACE_NAME